FROM node:18-alpine
#https://stackoverflow.com/questions/57573992/use-nodemon-with-docker-and-docker-compose
# Create app directory
WORKDIR /app
RUN apk add --no-cache mosquitto-clients bash
# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nodejs

COPY package*.json ./

RUN npm ci

# Bundle app source
COPY . .

#RUN chown -R node /app/node_modules
#USER nodejs


CMD [ "npm", "run", "start:dev" ]